[options]
base_path = "$config_dir"
output_path = "$config_dir/tables/experiments-cvpr"
cache_dir = "$config_dir/tables/cache"
show_values_failed_runs = false
screenread = true
#overwrite_cache = true


################################################################################
################################################################################

[[experiments]]
name = "povar"
display_name = "PoVar (ours)"
pattern = "eccv_varpro_povar/*/eccv_varpro_povar/*povar*"

[[experiments]]
name = "poba"
display_name = "PoBA [23]"
pattern = "eccv_poba/*/eccv_poba/*povar*"

[[experiments]]
name = "pose"
display_name = "pOSE [11]"
pattern = "eccv_pose/*/eccv_pose/*varproj*"

[[experiments]]
name = "varproj"
display_name = "iterative"
pattern = "eccv_varpro_povar/*/eccv_varpro_povar/*varproj*"





################################################################################
################################################################################

[[substitutions]]
EXPERIMENTS = [
    "povar",
    "poba",
    "pose",
    "varproj",
]
RELATIVE_TO_EXPERIMENT = "povar"

[[substitutions]]
TOLERANCES = [1e-2, 3e-3, 1e-3]
#YLIM_TOLERANCE_TOP = 1.75
#YLIM_TOLERANCE_BOTTOM = -0.1

YLIM_TOLERANCE_TOP = 3.5
YLIM_TOLERANCE_BOTTOM = -1.5


################################################################################
################################################################################
# [[results]]
# class = "section"
# name = "cvpr paper plots"
# pagewidth = "30cm"
# show = true

#[[results]]
#show = true
#class = "plot"
#type = "performance_profile"
#name = "all"
##filter_regex = "trafalgar|dubrovnik|venice|final"
#reverse_zorder = true
#experiments = "<EXPERIMENTS>"
#tolerances = "<TOLERANCES>"
#xlimits.right = [5,5,5]

[[results]]
show = true
 class = "plot"
 name = "convergence"
 type = "bal_cost"
 plot_tolerances = true
 tolerances = "<TOLERANCES>"
 bal_cost_include = ["cost_time"]
 #figsize = [3.2, 2.7]
 figsize = [5, 4]
 ylabel = true
 plot_cost_semilogy = true
 ylim_tolerance.bottom = "<YLIM_TOLERANCE_BOTTOM>"
 ylim_tolerance.top = "<YLIM_TOLERANCE_TOP>"
 xlim_time.left = -0.04
 xlim_time.right = 50.0
 reverse_zorder = true
 title = "dubrovnik253"
 sequence = "dubrovnik253"
 experiments = "<EXPERIMENTS>"

#[[results]]
#show = true
#class = "plot"
#name = "convergence"
#type = "bal_cost"
#plot_tolerances = true
#bal_cost_include = ["cost_time"]
#figsize = [3.2, 2.7]
#ylabel = false
#plot_cost_semilogy = true
#ylim_tolerance.bottom = "<YLIM_TOLERANCE_BOTTOM>"
#ylim_tolerance.top = "<YLIM_TOLERANCE_TOP>"
#xlim_time.left = -0.12
#xlim_time.right = 6
#reverse_zorder = true
#title = "trafalgar170"
#sequence = "trafalgar170"
#experiments = "<EXPERIMENTS>"

#[[results]]
#show = true
#class = "plot"
#name = "convergence"
#type = "bal_cost"
#plot_tolerances = true
#tolerances = "<TOLERANCES>"
#bal_cost_include = ["cost_time"]
#figsize = [3.2, 2.7]
#ylabel = false
#plot_cost_semilogy = true
#ylim_tolerance.bottom = "<YLIM_TOLERANCE_BOTTOM>"
#ylim_tolerance.top = "<YLIM_TOLERANCE_TOP>"
#xlim_time.left = -1.6
#xlim_time.right = 80
#reverse_zorder = true
#title = "venice1158"
#sequence = "venice1158"
#experiments = "<EXPERIMENTS>"

#[[results]]
#show = true
#class = "plot"
#name = "convergence"
#type = "bal_cost"
#plot_tolerances = true
#tolerances = "<TOLERANCES>"
#bal_cost_include = ["cost_time"]
#figsize = [3.2, 2.7]
#ylabel = false
#plot_cost_semilogy = true
#ylim_tolerance.bottom = "<YLIM_TOLERANCE_BOTTOM>"
#ylim_tolerance.top = "<YLIM_TOLERANCE_TOP>"
#xlim_time.left = -20
#xlim_time.right = 1000
#reverse_zorder = true
#title = "final4585"
#sequence = "final4585"
#experiments = "<EXPERIMENTS>"

#[[results]]
#show = true
#class = "plot"
#type = "memory"
##legend_loc = false
#problem_size_variants = ["obs"]
#figsize = [5,3]
#best_fit_line = false
#reverse_zorder = true
#name = "ladybug"
#filter_regex = "ladybug"
#experiments = "<EXPERIMENTS>"


################################################################################
################################################################################
# [[results]]
# class = "section"
# name = "performance profiles as seperate plots for poster"
# pagewidth = "30cm"
# show = true
#
# [[results]]
# show = true
# class = "plot"
# type = "performance_profile"
# name = "all_tau1em1"
# reverse_zorder = true
# experiments = "<EXPERIMENTS>"
# tolerances = [1e-2]
# xlimits.right = [5]
#
# [[results]]
# show = true
# class = "plot"
# type = "performance_profile"
# name = "all_tau1em2"
# reverse_zorder = true
# experiments = "<EXPERIMENTS>"
# tolerances = [3e-3]
# xlimits.right = [5]
#
# [[results]]
# show = true
# class = "plot"
# type = "performance_profile"
# name = "all_tau1em3"
# reverse_zorder = true
# experiments = "<EXPERIMENTS>"
# tolerances = [1e-3]
# xlimits.right = [5]

